version: "3.9"
services:
  web:
    image: ffrias9/wordpress:1.0
    ports: 
      - "8080:8080"
    volumes:
      - web:/var/www/html
    networks:
      wordpress:
        ipv4_address: 192.168.1.101
    depends_on:
      - db

  db:
    image: ffrias9/mariadb:2.0
    ports:
      - "3306:3306"
    env_file:
      - vars.env
    volumes:
      - database:/var/lib/mysql
    networks:
      wordpress:
        ipv4_address: 192.168.1.100

  reverse_proxy:
    image: ffrias9/nginx:1.3
    ports:
      - "8081:8081"
    env_file:
      - vars.env
    volumes:
      - reverse_proxy:/var/www/html
    networks:
      wordpress:
        ipv4_address: 192.168.1.102
    depends_on:
      - web

volumes:
  web:
  database:
  reverse_proxy:

networks:
  wordpress:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
