version: "3"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped
    networks:
      compose_wordpress:
        ipv4_address: 192.168.1.10

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      compose_wordpress:
        ipv4_address: 192.168.1.20

networks:
  compose_wordpress:
    external:
      name: compose_wordpress
