version: "3.9"
services:
  web:
    image: my_wordpress:latest
    ports: 
      - "8080:8080"
    volumes:
      - web:/var/www/html
    networks:
      wordpress:
        ipv4_address: 192.168.1.101
    depends_on:
      - db

  db:
    image: my_mariadb:latest
    ports:
      - "3306:3306"
    environment:
      ROOT_PASSWD: "toor"
      NEW_USER: "wordpress"
      NEW_USER_HOST: "%"
      NEW_USER_PASSWD: "Passw0rd!"
      NEW_DATABASE: "wordpress"
    volumes:
      - database:/var/lib/mysql
    networks:
      wordpress:
        ipv4_address: 192.168.1.100

volumes:
  web:
  database:

networks:
  wordpress:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
